### ISSUE TITLE
Refactor UI for homepage

### ISSUE THREAD

**Issue by hnngo** [fc5y/user-fe#157]
https://www.figma.com/file/MgABnSes20bkPJzZ8eoo7Q/Untitled?node-id=6%3A39

![image](https://user-images.githubusercontent.com/43344276/126678043-1c42a610-6265-4e08-acaf-3cf5702beed3.png)

There is a request to refactor the homepage UI. The design detail can be found in the figma link above.

**Comment by kc97ble** [comment]
The container's width, can be set to either 900px (same as the current implementation) or 948px (same as the Figma file).
