### ISSUE TITLE
Error material link in Contest Detail

### ISSUE THREAD

**Issue by hnngo** [fc5y/user-fe#168]
Currently, we can access materials through contest table like this
![image](https://user-images.githubusercontent.com/43344276/132103170-19f2f669-f51b-46fa-af20-778cf1255aa0.png)

But there is a problem when we access the material links in contest detail page like this. They are all being redirected to `about:blank`
![image](https://user-images.githubusercontent.com/43344276/132103200-e656ca14-993f-45be-8f1a-293b2b74e8f7.png)

**Comment by kc97ble** [comment]
Em cũng đang định report vấn đề tương tự 

![Screenshot_20210918_140750](https://user-images.githubusercontent.com/7184368/133878251-2c59a1c0-0c77-4288-ace2-7820ce7463b3.png)

**Comment by kc97ble** [comment]
This issue needs more priority because the feature is used frequently.
