### ISSUE TITLE
[FE] Thông báo (announcements)

### ISSUE THREAD

**Issue by kc97ble** [fc5y/user-fe#175]
![image](https://user-images.githubusercontent.com/7184368/135299620-578d9eb7-8f1a-49af-b140-ed3b8e95af82.png)

https://www.figma.com/file/Il87wn6Q1pAM5AugVpCMXd/Prototype?node-id=1994%3A8418

**Comment by kc97ble** [comment]
![image](https://user-images.githubusercontent.com/7184368/135299606-f243a1f0-9deb-455a-bffa-9d070d8320c2.png)

**Comment by hnngo** [comment]
Documentation https://docs.google.com/document/d/1Mcmf1_NLpnvs3Xj063aa1fPF1gDhdoFaT4z-SoV6Q4E/edit?usp=sharing
