### ISSUE TITLE
Need to extend the click area of username in Navbar

### ISSUE THREAD

**Issue by hnngo** [fc5y/user-fe#67]
**Version**: _fyt-1.4_
**Where to find**:  Top right of Navbar
![image](https://user-images.githubusercontent.com/43344276/95656007-e9e5e380-0b3d-11eb-809a-df59bd5fbcc6.png)

**Current behavior**: Currently, we only can click on the icon to expand the dropdown. 
**Expected behaviour**: We need to extend the click area to include the text username or perfectly a rectangle cover both username and icon with a padding size of 5px

**Comment by ITES7321** [comment]
Hi! Can I work on this issue?

**Comment by hnngo** [comment]
> Hi! Can I work on this issue?

Hi @ITES7321, thanks for interested in this project. Currently, this project is not an open-source project, hence I am sorry to say that this issue is not for unauthorized person. Thank you once again.

**Comment by hnngo** [comment]
Resolved in https://github.com/fc5y/user-fe/pull/72
